[package]
name = "euforia-audio-experience"
description = "Euforia-Audio-Experience: real-time audio experience"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "euforia_audio_experience_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
audio-capture = { path = "../native/audio-capture" }
spectrum-analysis = { path = "../native/analysis" }
