// Generated by native/analysis (wire.rs) — do not edit. Regenerate with
// `UPDATE_LAYOUT=1 cargo test -p spectrum-analysis --test wire`.

/** Record tags of the analysis event stream. */
export const TAG = { frame: 1, onset: 2, beat: 3, clock: 4 } as const;

export const RECORD = { frame: 83, onset: 6, beat: 9, clock: 3 } as const;

/** Field name → [offset in the record, length]. */
export const FRAME_FIELDS = {
  sample: [1, 1],
  time: [2, 1],
  presence: [3, 1],
  sounding: [4, 1],
  silent: [5, 1],
  noiseFloorDb: [6, 1],
  clipping: [7, 1],
  bandDb: [8, 8],
  bandRel: [16, 8],
  energyConfidence: [24, 1],
  loudnessMomentary: [25, 1],
  loudnessShort: [26, 1],
  loudnessLong: [27, 1],
  loudnessSlope: [28, 1],
  loudnessCurvature: [29, 1],
  loudnessRel: [30, 1],
  centroidHz: [31, 1],
  rolloffHz: [32, 1],
  flatness: [33, 1],
  flux: [34, 1],
  fluxLow: [35, 1],
  fluxMid: [36, 1],
  fluxHigh: [37, 1],
  timbreConfidence: [38, 1],
  percussive: [39, 1],
  percussiveLow: [40, 1],
  percussiveMid: [41, 1],
  percussiveHigh: [42, 1],
  harmonicDb: [43, 1],
  percussiveDb: [44, 1],
  onsetStrength: [45, 1],
  onsetDensity: [46, 1],
  tempoBpm: [47, 1],
  tempoConfidence: [48, 1],
  resonatorBpm: [49, 1],
  resonatorConfidence: [50, 1],
  beatBpm: [51, 1],
  beatPhase: [52, 1],
  barPhase: [53, 1],
  beatConfidence: [54, 1],
  downbeatConfidence: [55, 1],
  nextBeatTime: [56, 1],
  chroma: [57, 12],
  chromaConfidence: [69, 1],
  key: [70, 1],
  keyConfidence: [71, 1],
  width: [72, 1],
  correlation: [73, 1],
  bandPan: [74, 8],
  stereoConfidence: [82, 1],
} as const;

export const ONSET_FIELDS = {
  sample: [1, 1],
  time: [2, 1],
  strength: [3, 1],
  region: [4, 1],
  low: [5, 1],
} as const;

export const BEAT_FIELDS = {
  sample: [1, 1],
  time: [2, 1],
  index: [3, 1],
  barPosition: [4, 1],
  downbeat: [5, 1],
  bpm: [6, 1],
  confidence: [7, 1],
  downbeatConfidence: [8, 1],
} as const;

export const CLOCK_FIELDS = {
  sample: [1, 1],
  age: [2, 1],
} as const;
