//! A flat encoding of the event stream for hosts across a boundary (Tauri
//! IPC, WebAssembly memory): each event is a record of f64 values starting
//! with a tag. Frames follow `FeatureFrame::LAYOUT`; onsets and beats have
//! fixed small layouts. `typescript_layout` renders the matching decoder
//! constants for the frontend, kept in sync by a test.

use crate::{BeatEvent, Event, FeatureFrame, OnsetEvent};

pub const TAG_FRAME: f64 = 1.0;
pub const TAG_ONSET: f64 = 2.0;
pub const TAG_BEAT: f64 = 3.0;

pub const ONSET_LAYOUT: &[(&str, usize)] = &[("sample", 1), ("time", 1), ("strength", 1), ("region", 1), ("low", 1)];
pub const BEAT_LAYOUT: &[(&str, usize)] = &[
    ("sample", 1),
    ("time", 1),
    ("index", 1),
    ("bar_position", 1),
    ("downbeat", 1),
    ("bpm", 1),
    ("confidence", 1),
    ("downbeat_confidence", 1),
];

/// Values in a record (tag included) for each event kind.
pub const FRAME_RECORD: usize = 1 + FeatureFrame::SIZE;
pub const ONSET_RECORD: usize = 1 + ONSET_LAYOUT.len();
pub const BEAT_RECORD: usize = 1 + BEAT_LAYOUT.len();
/// The largest record.
pub const MAX_RECORD: usize = FRAME_RECORD;

/// Writes `event` at the start of `out` (at least `MAX_RECORD` long); returns the values written.
pub fn encode(event: &Event, out: &mut [f64]) -> usize {
    match event {
        Event::Frame(frame) => {
            out[0] = TAG_FRAME;
            frame.export(&mut out[1..FRAME_RECORD]);
            FRAME_RECORD
        }
        Event::Onset(OnsetEvent { sample, time, strength, region, low }) => {
            out[..ONSET_RECORD].copy_from_slice(&[TAG_ONSET, *sample as f64, *time, f64::from(*strength), f64::from(*region), f64::from(*low)]);
            ONSET_RECORD
        }
        Event::Beat(BeatEvent { sample, time, index, bar_position, downbeat, bpm, confidence, downbeat_confidence }) => {
            out[..BEAT_RECORD].copy_from_slice(&[
                TAG_BEAT,
                *sample as f64,
                *time,
                *index as f64,
                f64::from(*bar_position),
                if *downbeat { 1.0 } else { 0.0 },
                f64::from(*bpm),
                f64::from(*confidence),
                f64::from(*downbeat_confidence),
            ]);
            BEAT_RECORD
        }
    }
}

/// TypeScript constants describing the records (generated; see the `wire` test).
pub fn typescript_layout() -> String {
    let fields = |layout: &[(&str, usize)]| -> String {
        let mut offset = 1;
        let mut out = String::new();
        for (name, len) in layout {
            out.push_str(&format!("  {}: [{offset}, {len}],\n", camel(name)));
            offset += len;
        }
        out
    };
    format!(
        "// Generated by native/analysis (wire.rs) — do not edit. Regenerate with\n\
         // `UPDATE_LAYOUT=1 cargo test -p spectrum-analysis --test wire`.\n\
         \n\
         /** Record tags of the analysis event stream. */\n\
         export const TAG = {{ frame: {TAG_FRAME}, onset: {TAG_ONSET}, beat: {TAG_BEAT} }} as const;\n\
         \n\
         export const RECORD = {{ frame: {FRAME_RECORD}, onset: {ONSET_RECORD}, beat: {BEAT_RECORD} }} as const;\n\
         \n\
         /** Field name → [offset in the record, length]. */\n\
         export const FRAME_FIELDS = {{\n{}}} as const;\n\
         \n\
         export const ONSET_FIELDS = {{\n{}}} as const;\n\
         \n\
         export const BEAT_FIELDS = {{\n{}}} as const;\n",
        fields(FeatureFrame::LAYOUT),
        fields(ONSET_LAYOUT),
        fields(BEAT_LAYOUT),
    )
}

fn camel(name: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for c in name.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}
