import { STRAND } from '../particles/MatterSeeds';
import { HARMONIC_WIDTH, NODES } from './HarmonicForm';
import { SIGNAL_ROWS, SIGNAL_SIZE } from './SignalForm';

/*
 * The form law: where one element of matter belongs when the matter takes a
 * form. Matter is never created for a shape: the same persistent elements are
 * claimed, strand by strand, by one of two forms generated by the signal, and
 * the rest stay free particles under the fields. What the law returns is an
 * anchor and how firmly it holds (0 = free); the field law turns it into a
 * force, so matter travels to a form, wobbles on it and leaves it — nothing is
 * placed. Written twice like the field law, GLSL and CPU reference, term by
 * term.
 *
 * A strand is STRAND elements in a row; its members alternate between two
 * sides, so along a form the strand is a zig-zag whose bonds and facets
 * (ParticleMatter) span it:
 *
 *   wave form      the strand is a patch of the surface swept by the waveform:
 *                  along the cycle × across the history. The cycle is bent
 *                  from a line into a ring (closure), wound by a number of
 *                  lobes (pitch), displaced outwards by the signal; the history
 *                  recedes along the axis. Width 0 = a filament along the curve.
 *   harmonic form  the strand belongs to three nodes: its sides start at two
 *                  of them and converge on the third as far as all three are
 *                  related (a polygon), or on their midpoint (a filament along
 *                  the pair); it is held only while the pair is related.
 *
 * Which form claims a strand is its key against the forms' shares: the low
 * keys go to the wave form, the high ones to the harmonic form, so matter
 * moves from one state to another strand by strand as the shares change.
 */

/** Order of the packed form values (`uForm[i]` in GLSL). */
const ORDER = ['wave', 'harmonic', 'closure', 'amplitude', 'ribbon', 'depth', 'ring', 'scale', 'fracture', 'head', 'frac', 'lobesLow', 'lobesHigh', 'levelLow', 'levelHigh'] as const;
export type FormValue = typeof ORDER[number];
/** Index of each value in the packed vector. */
export const FORM = Object.fromEntries(ORDER.map((key, i) => [key, i])) as { readonly [K in FormValue]: number };
export const FORM_VALUES = ORDER.length;

/** Length of a strand along the signal's curve (cycles of the curve). */
const PIECE = 0.035;
/** Radius of the high voice's ring relative to the low one's. */
const HIGH_RING = 0.62;
/** Width of the band of keys over which a strand passes from free to claimed. */
export const EDGE = 0.04;
/** Deepest history position used (rows): the last row is kept for interpolation. */
const DEEPEST = SIGNAL_ROWS - 2;
/** Amplitude lost by the oldest row. */
const FADE = 0.6;
/** How far along the way to the third node a strand's last pair sits (< 1: the two sides never coincide). */
const SPAN = 3.5;

const defines = ORDER.map((key, i) => `#define M_${key.replace(/[A-Z]/g, (c) => `_${c}`).toUpperCase()} uForm[${i}]`).join('\n');

/**
 * GLSL ES 3.00. Needs the field law's uniforms (F_LATERAL, F_TURN, F_RADIUS) declared before it.
 * `form` = the element's form seed (see MatterSeeds), `member` its index in the strand.
 * Returns the anchor xyz and how firmly it holds, 0..1.
 */
export const formLawGlsl = /* glsl */ `
uniform float uForm[${FORM_VALUES}];
uniform sampler2D tSignal;
uniform sampler2D tHarmonic;
${defines}

float signalRow(int row, float cycles) {
  float p = fract(cycles) * ${SIGNAL_SIZE}.0;
  int i = min(int(p), ${SIGNAL_SIZE - 1});
  return mix(texelFetch(tSignal, ivec2(i, row), 0).r, texelFetch(tSignal, ivec2((i + 1) % ${SIGNAL_SIZE}, row), 0).r, p - float(i));
}

// A voice's signal \`rows\` rows back in its history. The live row has age 0; row j ≥ 1 has age j − 1 + frac.
float signalAt(float voice, float rows, float cycles) {
  float back = rows + 1.0 - M_FRAC;
  int j = int(back);
  float t = back - float(j);
  if (back < 1.0) { j = 0; t = rows / max(M_FRAC, 1e-4); }
  int base = int(voice) * ${SIGNAL_ROWS};
  int head = int(M_HEAD);
  int r0 = base + (head - min(j, ${SIGNAL_ROWS - 1}) + ${SIGNAL_ROWS}) % ${SIGNAL_ROWS};
  int r1 = base + (head - min(j + 1, ${SIGNAL_ROWS - 1}) + ${SIGNAL_ROWS}) % ${SIGNAL_ROWS};
  return mix(signalRow(r0, cycles), signalRow(r1, cycles), t);
}

vec3 placed(vec3 p) {
  float c = cos(F_TURN), s = sin(F_TURN);
  return vec3(c * p.x - s * p.y + F_LATERAL, s * p.x + c * p.y, p.z);
}

vec3 waveAnchor(vec4 form, int member) {
  float voice = floor(form.w);
  float u = form.x + (float(member / 2) / 3.0 - 0.5) * ${PIECE};
  float rows = clamp((form.w - voice) * ${DEEPEST}.0 + (float(member % 2) - 0.5) * M_RIBBON, 0.0, ${DEEPEST}.0);
  float lobes = voice > 0.5 ? M_LOBES_HIGH : M_LOBES_LOW;
  float n0 = floor(lobes);
  float w = mix(signalAt(voice, rows, u * n0), signalAt(voice, rows, u * (n0 + 1.0)), lobes - n0);
  float age = rows / ${DEEPEST}.0;
  // The cycle as an arc of constant length: a line when open, a ring when closed, centred on its own middle.
  float theta = max(M_CLOSURE, 0.02) * 6.2831853;
  float phi = (fract(u) - 0.5) * theta;
  float R = 6.2831853 * M_RING * (voice > 0.5 ? ${HIGH_RING} : 1.0) * (0.5 + 0.5 * M_CLOSURE) / theta;
  float h = 0.5 * theta;
  float out_ = M_AMPLITUDE * (1.0 - ${FADE} * age) * w;
  return placed(vec3(R * sin(phi) + sin(phi) * out_, R * (sin(h) / h - cos(phi)) - cos(phi) * out_, (0.5 - age) * M_DEPTH));
}

vec4 harmonicAnchor(vec4 form, int member) {
  int code = int(form.z + 0.5);
  int a = code % ${NODES}, b = (code / ${NODES}) % ${NODES}, c = code / ${NODES * NODES};
  vec3 A = texelFetch(tHarmonic, ivec2(a, 0), 0).xyz;
  vec3 B = texelFetch(tHarmonic, ivec2(b, 0), 0).xyz;
  vec3 C = texelFetch(tHarmonic, ivec2(c, 0), 0).xyz;
  float pair = texelFetch(tHarmonic, ivec2(b, 1 + a), 0).r;
  float triple = min(texelFetch(tHarmonic, ivec2(c, 1 + a), 0).r, texelFetch(tHarmonic, ivec2(c, 1 + b), 0).r);
  vec3 apex = mix(0.5 * (A + B), C, smoothstep(0.1, 0.45, triple));
  vec3 p = mix(member % 2 == 0 ? A : B, apex, float(member / 2) / ${SPAN}) * (F_RADIUS * M_SCALE);
  return vec4(placed(p), smoothstep(0.08, 0.35, pair));
}

vec4 formAnchor(vec4 form, int member) {
  float inWave = 1.0 - smoothstep(M_WAVE - ${EDGE}, M_WAVE, form.y);
  float inHarmonic = smoothstep(1.0 - M_HARMONIC, 1.0 - M_HARMONIC + ${EDGE}, form.y);
  float whole = 1.0 - M_FRACTURE;
  // A voice that is not there holds none of its matter.
  if (inWave > 0.0) return vec4(waveAnchor(form, member), inWave * whole * smoothstep(0.05, 0.3, form.w >= 1.0 ? M_LEVEL_HIGH : M_LEVEL_LOW));
  if (inHarmonic > 0.0) {
    vec4 anchor = harmonicAnchor(form, member);
    return vec4(anchor.xyz, anchor.w * inHarmonic * whole);
  }
  return vec4(0.0);
}
`;

/** Result of `formAnchor`: anchor xyz and hold. Reused. */
export const anchorOut = new Float64Array(4);

const smoothstep = (lo: number, hi: number, x: number): number => {
  const t = Math.min(1, Math.max(0, (x - lo) / (hi - lo)));
  return t * t * (3 - 2 * t);
};
const fract = (x: number): number => x - Math.floor(x);

function signalRow(signal: Float32Array, row: number, cycles: number): number {
  const p = fract(cycles) * SIGNAL_SIZE, i = Math.min(Math.floor(p), SIGNAL_SIZE - 1);
  const at = row * SIGNAL_SIZE, a = signal[at + i];
  return a + (signal[at + (i + 1) % SIGNAL_SIZE] - a) * (p - i);
}

function signalAt(signal: Float32Array, voice: number, rows: number, cycles: number, head: number, frac: number): number {
  const back = rows + 1 - frac;
  let j = Math.floor(back), t = back - j;
  if (back < 1) { j = 0; t = rows / Math.max(frac, 1e-4); }
  const base = voice * SIGNAL_ROWS;
  const r0 = base + (head - Math.min(j, SIGNAL_ROWS - 1) + SIGNAL_ROWS) % SIGNAL_ROWS;
  const r1 = base + (head - Math.min(j + 1, SIGNAL_ROWS - 1) + SIGNAL_ROWS) % SIGNAL_ROWS;
  const a = signalRow(signal, r0, cycles);
  return a + (signalRow(signal, r1, cycles) - a) * t;
}

function place(x: number, y: number, z: number, hold: number, lateral: number, turn: number): Float64Array {
  const c = Math.cos(turn), s = Math.sin(turn);
  anchorOut[0] = c * x - s * y + lateral; anchorOut[1] = s * x + c * y; anchorOut[2] = z; anchorOut[3] = hold;
  return anchorOut;
}

/**
 * CPU reference of `formAnchor` for element `i` (stride 4 in `form`). `m` is
 * the packed form vector; `lateral`, `turn` and `radius` are the field law's
 * (packed) values; `signal` and `harmonic` the data of the two forms.
 * Writes `anchorOut`.
 */
export function formAnchor(
  form: Float32Array, i: number, m: Float32Array, lateral: number, turn: number, radius: number, signal: Float32Array, harmonic: Float32Array,
): Float64Array {
  const at = i * 4, member = i % STRAND, pair = Math.floor(member / 2), odd = member % 2;
  const key = form[at + 1];
  const inWave = 1 - smoothstep(m[FORM.wave] - EDGE, m[FORM.wave], key);
  const inHarmonic = smoothstep(1 - m[FORM.harmonic], 1 - m[FORM.harmonic] + EDGE, key);
  const whole = 1 - m[FORM.fracture];
  if (inWave > 0) {
    const voice = Math.floor(form[at + 3]);
    const u = form[at] + (pair / 3 - 0.5) * PIECE;
    const rows = Math.min(DEEPEST, Math.max(0, (form[at + 3] - voice) * DEEPEST + (odd - 0.5) * m[FORM.ribbon]));
    const lobes = voice > 0.5 ? m[FORM.lobesHigh] : m[FORM.lobesLow], n0 = Math.floor(lobes);
    const head = Math.floor(m[FORM.head]), frac = m[FORM.frac];
    const w0 = signalAt(signal, voice, rows, u * n0, head, frac);
    const w = w0 + (signalAt(signal, voice, rows, u * (n0 + 1), head, frac) - w0) * (lobes - n0);
    const age = rows / DEEPEST;
    const closure = m[FORM.closure], theta = Math.max(closure, 0.02) * 6.2831853, phi = (fract(u) - 0.5) * theta;
    const R = 6.2831853 * m[FORM.ring] * (voice > 0.5 ? HIGH_RING : 1) * (0.5 + 0.5 * closure) / theta;
    const h = 0.5 * theta, out = m[FORM.amplitude] * (1 - FADE * age) * w;
    const sin = Math.sin(phi), cos = Math.cos(phi);
    const voiced = smoothstep(0.05, 0.3, voice > 0.5 ? m[FORM.levelHigh] : m[FORM.levelLow]);
    return place(R * sin + sin * out, R * (Math.sin(h) / h - cos) - cos * out, (0.5 - age) * m[FORM.depth], inWave * whole * voiced, lateral, turn);
  }
  if (inHarmonic > 0) {
    const code = Math.floor(form[at + 2] + 0.5);
    const a = code % NODES, b = Math.floor(code / NODES) % NODES, c = Math.floor(code / (NODES * NODES));
    const related = harmonic[((1 + a) * HARMONIC_WIDTH + b) * 4];
    const triple = Math.min(harmonic[((1 + a) * HARMONIC_WIDTH + c) * 4], harmonic[((1 + b) * HARMONIC_WIDTH + c) * 4]);
    const toThird = smoothstep(0.1, 0.45, triple), t = pair / SPAN, scale = radius * m[FORM.scale];
    const from = (odd === 0 ? a : b) * 4;
    let x = 0, y = 0, z = 0;
    for (let k = 0; k < 3; k++) {
      const middle = 0.5 * (harmonic[a * 4 + k] + harmonic[b * 4 + k]);
      const apex = middle + (harmonic[c * 4 + k] - middle) * toThird;
      const value = (harmonic[from + k] + (apex - harmonic[from + k]) * t) * scale;
      if (k === 0) x = value; else if (k === 1) y = value; else z = value;
    }
    return place(x, y, z, smoothstep(0.08, 0.35, related) * inHarmonic * whole, lateral, turn);
  }
  anchorOut[0] = anchorOut[1] = anchorOut[2] = anchorOut[3] = 0;
  return anchorOut;
}
